### ISSUE TITLE
Error on running `drush sql-connect` to import DB

### ISSUE THREAD

**Issue by mccrodp** [mccrodp/drupal-docker-compose#1]
On php-fpm-nginx branch there is an error on running `drush sql-connect`.

```
docker-compose exec web `drush sql-connect` < ../databases/db_dump.sql
Unable to load class Drush\Sql\Sql                                                                                                                                                                                        [error]
exception 'Drush\Sql\SqlException' with message 'Unable to find a matching SQL Class. Drush cannot find your database connection details.' in                                                                             [error]
/Users/paulmccrodden/.composer/vendor/drush/drush/commands/sql/sql.drush.inc:593
Stack trace:
#0 /Users/paulmccrodden/.composer/vendor/drush/drush/commands/sql/sql.drush.inc(236): drush_sql_get_class()
#1 [internal function]: drush_sql_connect()
#2 /Users/paulmccrodden/.composer/vendor/drush/drush/includes/command.inc(366): call_user_func_array('drush_sql_conne...', Array)
#3 /Users/paulmccrodden/.composer/vendor/drush/drush/includes/command.inc(217): _drush_invoke_hooks(Array, Array)
#4 [internal function]: drush_command()
#5 /Users/paulmccrodden/.composer/vendor/drush/drush/includes/command.inc(185): call_user_func_array('drush_command', Array)
#6 /Users/paulmccrodden/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#7 /Users/paulmccrodden/.composer/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 /Users/paulmccrodden/.composer/vendor/drush/drush/drush.php(12): drush_main()
#9 {main}
Execute a command in a running container

Usage: exec [options] SERVICE COMMAND [ARGS...]

Options:
    -d                Detached mode: Run command in the background.
    --privileged      Give extended privileges to the process.
    --user USER       Run the command as this user.
    -T                Disable pseudo-tty allocation. By default `docker-compose exec`
                      allocates a TTY.
    --index=index     index of the container if there are multiple
                      instances of a service [default: 1]
```

**Comment by mccrodp** [comment]
Seems like this is drush command is evaluated on the host first, which gives an error, which is correct.

To run on the container it seems we can run the following, but is not performant as we need to increase the timeout `export COMPOSE_HTTP_TIMEOUT=300` first before running `docker-compose up`.

```
docker-compose exec -d web drush sql-cli < ../db_dump.sql
```

Will stick to running `docker exec -i`
